FROM formula-trend-base2
  
# Set the working directory to /app
WORKDIR /app
ADD . /app
# Run sample_bot.py when the container launches, you should replace it with your program
ENTRYPOINT ["python3.6", "sample_bot.py"]